workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

railway-deploy:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  variables:
    SVC_ID: RAILWAY_SERVICE_NAME
    RAILWAY_TOKEN: ${RAILWAY_TOKEN}
  script:
    - railway login $RAILWAY_TOKEN
    - railway up --service=$SVC_ID
