# Generated by Django 5.1.7 on 2025-04-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboardmapping',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='keyboardmapping',
            name='name',
            field=models.CharField(default='Unamed Mapping', max_length=50),
        ),
    ]
