# Generated by Django 5.1.7 on 2025-04-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_keyboardmapping_description_keyboardmapping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboardmapping',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyboardmapping',
            name='num_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyboardmapping',
            name='num_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
