# Generated by Django 5.1.7 on 2025-04-17 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_keyboardmapping_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboardmapping',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
