# Generated by Django 5.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='default_mapping_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]

